apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306        # this is the port on which the MySQL service will be exposed
      targetPort: 3306    # this is the port on which the MySQL container is listening
      nodePort: 30306      # this is the port on which the service will be accessible from outside the cluster