apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  selector:
    app.kubernetes.io/name: my-backend
  ports:
    - protocol: http
      name: http
      port: 5173
      targetPort: 5173
  type: NodePort