apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  labels:
    app: my-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
      - name: dockerhubwala
        image: priyadarshiu/mybackendimage:03
        ports:
        - containerPort: 5173
